name: Continuous Integration

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install node modules
        run: |
          npm ci
      - name: Run test
        run: |
          npm run ci
